### ISSUE TITLE
Background panorama

### ISSUE THREAD

**Issue by FrMo** [gak/gravit#39] opened 2012-01-05 08:43 UTC
how about adding a feature to display some kind of "background image"?
I am thinking of some stars and faint galaxies backgrounds, like the famous "hubble ultra deep field".

It might be possible to put a large sphere around the center of view, with an image as texture;
this way the background would automaticially move when rotating the view.

**Comment by gak** [comment] 2012-01-05 20:58
I've made an issue for this already albeit a not very descriptive one. I'll amend your comment to it so it is more descriptive.

Duplicate of #2

**Closed as completed by gak** 2012-01-05 20:58 UTC
